Repository octokit/oauth-authorization-url.js, pull requests merged in 2022-07, with the labels that each got.

#186 ci: stop testing against NodeJS v10, v12
  .github/workflows/test.yml
  package.json
Labels: blocked, maintenance

#189 Add prettier to project
  README.md
  package-lock.json
  package.json
Labels: maintenance

#188 ci(test): use test_matrix and test jobs
  .github/workflows/test.yml
Labels: blocked, maintenance

#192 [deps] updates pika/pack to a non vulnerable version
  package-lock.json
  package.json
Labels: dependencies, maintenance
